### PR TITLE
feat(http): add tests for fastify server

### LINKED ISSUE #869: Does PostGraphile support Fastify?
https://www.fastify.io/docs/latest/Middlewares/

Would be good to add it to the list of servers that we can be mounted as a middleware.

### PR DESCRIPTION
**Pull request by benjie**
Fastify passes our core test suite 💯 `fastify.use(postgraphile(...))`

It doesn't seem to work with mounting a middleware on a subpath right now (i.e. `fastify.use('/path/to', postgraphile(...))`), presumably it's not doing `originalUrl` / `url` manipulation?

Fixes #869

### CODE REVIEW

**Comment by ken0x0a** [comment]
I think
```
fastify.use('/path/to', postgraphile(..., ..., { graphqlRoute: '/path/to', ... }))
```

is also works fine, as followings works fine

```
function postgraphileService(fastify ) {
  app.use(postgraphile(..., ..., { graphqlRoute: '/path/to', ... }))
}
fastify.register(postgraphileService, { prefix: '/path/to' })
```

**Comment by benjie** [comment]
Maybe they’ve added originalUrl support?

If you’re relying on this I strongly suggest you open a PR upgrading fastify and enabling the tests I disabled; without them there’s a higher chance of regression.

**Comment by ken0x0a** [comment]
@benjie Thank you for a reply! I know you are very busy right now.

Actually, I'd rather trying to do **[even-lower-level-access](https://www.graphile.org/postgraphile/usage-schema/#even-lower-level-access)**, to get object

which `operationName` as key, and
`sql` as value,

to make API even faster,
without `parsing query`, `validate args`, `JSON.stringify` & `JSON.parse`.
As I'm using persist query, those are too much work for every request.

Postgraphile is awesome!
I feel, Postgraphile become even faster after upgraded to 4.4.1.
Thank you for your tremendous works & support!

I'll try PR if I couldn't do sth mentioned above or not satisfied with that.

**Comment by ken0x0a** [comment]
@benjie 
Would you give me hint to solve following error? Thank you!

```
   Cannot find module '../../assets/favicon.ico' from 'createPostGraphileHttpRequestHandler.ts'

    However, Jest was able to find:
    	'http/createPostGraphileHttpRequestHandler.ts'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['ts', 'js', 'ico', 'html', 'json'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

    However, Jest was able to find:
    	'./postgraphile.ts'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['ts', 'js', 'ico', 'html', 'json'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:229:17)
      at Object.<anonymous> (src/postgraphile/http/file:/Users/k/GitHub/postgraphile/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts:44:1)
```
